name: issue_to_notion_card
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Card Creator
        uses: dodo4114/issue-to-notion@v1.0.1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: https://www.notion.so/dodo4114/aebe312a066c465494fb1eb6997060b0?v=95652d72244a44bd97d39b6057c51dc0
